name: .venv
channels:
- conda-forge
dependencies:
- python=3.9
- pip=24.0
- pip:
  - azureml-fsspec==1.3.1
  - cupy-cuda12x==13.0.0
  - pandas==2.2.1
  - spacy-lookups-data==1.0.5
  - spacy-transformers==1.3.4
  - spacy==3.7.5
