name: .venv
channels:
- conda-forge
dependencies:
- python=3.9
- pip=24.0
- pip:
  - azure-ai-ml==1.15.0
  - azure-identity==1.15.0
  - azure-storage-blob==12.19.1
  - azureml-contrib-services==1.55.0
  - azureml-inference-server-http==1.2.0
  - cupy-cuda12x==13.0.0
  - ftfy==6.2.0
  - pydantic==2.6.4
  - python-dotenv==1.0.1
  - requests==2.31.0
  - spacy-lookups-data==1.0.5
  - spacy-transformers==1.3.4
  - spacy==3.7.5
  - tenacity==8.2.3
