version: "3.8"

services:
    azure:
        build: .
        image: <acr>.azurecr.io/<repo>:prodigy
        container_name: <repo>
        ports:
            - 8080:80
        volumes:
            - ./data:/prodigy/data
        environment:
            - AzureWebJobsAzureWebJobsStorage={}
