parameters:
  - name: pipelineName
    type: string

steps:

- task: AzureCLI@2
  displayName: 'Register Environment To Shared Registry'
  inputs:
    connectedServiceNameARM: $(serviceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: python ado/scripts/environment_shared.py -s $(subscriptionId) -rg $(resourceGroupName) -ws $(workspaceName) -env $(environmentName) -p ${{ parameters.pipelineName }} -rn $(registryName)
