parameters:
  - name: pipelineName
    type: string

steps:

- task: AzureCLI@2
  displayName: 'Train Model in AML'
  inputs:
    connectedServiceNameARM: $(serviceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: python ado/scripts/train.py -s $(subscriptionId) -rg $(resourceGroupName) -ws $(workspaceName) -env $(environmentName) -p ${{ parameters.pipelineName }} -da $(dataAssetName) -c $(computeName) -r $(repoName) -j $(jobNumber)
