version: "3.8"

services:
    azure:
        build: .
        image: ${acr}.azurecr.io/${repo}:streamlit
        container_name: ${repo}
        ports:
            - 8080:8080
        volumes:
            - ./data:/app/data
        environment:
            - AzureWebJobsAzureWebJobsStorage=${AzureWebJobsAzureWebJobsStorage}
